### ISSUE TITLE
Feature 7: User can use forget password link to reset password

### ISSUE THREAD

**Issue by hannahshamb** [hannahnengel/hate-mate#14]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
User can use the forgot password link to and reset password.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
User will click the link below the password input, and email will be sent to the user, and the user will click the link in the email to be redirected to reset their password. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![FEATURE 7_Desktop](https://user-images.githubusercontent.com/90408240/207519217-b204476f-41ce-40ea-a6e6-500c9934cb3e.png)
![FEATURE 7_Mobile](https://user-images.githubusercontent.com/90408240/207519220-7a639148-97a5-486f-96af-2e12b12139ed.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server
- [x] Update `server/index.js` to include route for forgot password that checks if user exists 
- [x] Update the forgot password route to create a one time reset password link valid for 15 minutes after the user is verified
- [x] Install nodemailer as a dependancy 
- [x] Add a HateMate png to the server folder to embed in the email to the user 
- [x] Create a email.js file that exports the sendUserEmail function that sends the user an email with the link to reset their password 
- [x] Update index.js to call the sendUserEmail function and pass all necessary parameters 
- [x] Update index.js with a get request to verify the user once they click the link to reset password
- [x] Update index.js with a post request method to update the user password based on the userId, password, and confirmed password from the reset password form 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client
- [x] Update AuthForm component to include Forgot Password Link
- [x] Create ForgotPassword Component that displays Forgot Password modal when clicked from Auth Form Sign in Form
- [x] Update ForgotPassword Component to send post request to server for forgot password
- [x] Update ForgotPassword Component to send user a message if the email does not exist in the system
- [x] Update the ForgotPassword Component to reset state back so the user can try a different email in the forgot password modal 
- [x] Update app.jsx to check if a user is trying to redirect to the ResetPassword page and if so, make a fetch request to verify the user / token again
- [x] Create a ResetPassword Component that includes a form for user to create a new password
- [x] Update the ResetPassword Component to call a post request from the form submit to reset the password

### 🧑‍⚕️ Clean Up
- [x] Fix photo uploads bug
- [x] Fixed small design updated on email.js
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
