### ISSUE TITLE
Bug: Photo Uploads Bug Fix

### ISSUE THREAD

**Issue by hannahshamb** [hannahnengel/hate-mate#19]
#### Desired Behavior
The app should successfully upload photos using multer3 in the correct AWS during production

#### Actual Behavior
The app is currently returning an error upon file upload

#### Steps to Reproduce
To trigger the bug, I have to test the app in production mode

## ✅ Task List
- [ ] Test the app in production mode
- [ ] Console.log everything 

- **Clean Up**
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
