### ISSUE TITLE
Feature 3: User can edit their profile information

### ISSUE THREAD

**Issue by hannahshamb** [hannahnengel/hate-mate#3]
## ⚙️ Feature
User can edit their profile information

## 📐 Functionality
User will be able to interact with their profile, click to edit, upload, or delete their profile photo that is displayed, and click to edit their information or their friend preferences. The profile also includes an option to edit hate selection preferences that are displayed (and will take the user to each specific category that they want to edit) or use the "retake quiz" button that allows the user to start the hate selections quiz over again and retake each category. 

## 🖼️ Wireframes

![FEATURE 3-Desktop](https://user-images.githubusercontent.com/90408240/191347672-1b01a498-7a8d-4d3b-9c00-79db430db740.png)
![FEATURE 3-Mobile](https://user-images.githubusercontent.com/90408240/191347665-55ac2c58-d34e-4547-a30f-f0e8a4f84466.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to include `fileName` in the `profilePics` table

### ☁️ Server

- [x] Update `server/index.js` to include a get categories by categoryId method
- [x] Update the `server/index.js` to include a get profile picture method 
- [x] Update the `server/index.js` to include a post profile picture method 
- [x] Create a Delete method in `server/index.js` to delete the existing profile picture
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update `Profile` component to take user to the corresponding profile info and friend preferences form pages when the corresponding edit icon is clicked 
- [x] Update `Profile-Info-Form` component to display confirm / cancel buttons if the user is editing information (instead of creating it for the first time)
- [x] Update `Profile-Info-Form` component to push new profile information to the server when user clicks confirm button and redirect to the profile page 
- [x] Update `Profile` component to display edit icons when hovering over the hate selections
- [x] Update `Profile` components to display corresponding hate selections page when edit icon is clicked
- [x] Update the `Hate-Selections-Input` component to display cancel confirm buttons when user is only meaning to edit that specific category selection (when clicking the edit icon on the specific category)
- [x] Update the  `Hate-Selections-Input` component to reroute to the profile after user cancels or confirms (and ensure confirm pushes new data to the database)
- [x] Create a `Photo-Modal` component and update the `Profile` component to display the modal when the camera icon is clicked
- [x] Update `Photo-Modal` component to upload the file uploaded picture and replace the placeholder image with uploaded image 
- [x] Update the `Photo-Modal` component to push the file uploaded image to the database
- [x] Update the `Photo-Modal` and the `Profile` component to fetch profile pictures from the database if there are any 
- [x] Edit `Photo-Modal` to delete the photo from the db when user clicks db button
- [x] Edit the `Photo-Modal` and `Profile` so when the modal is closed, the db is checked for profile pictures and appropriate picture is displayed (or none) 

### 🧑‍⚕️ Clean Up

- [x] Clean up confirm cancel button formatting
- [x] Clean up `Hate-Selections-Inputs` errors and formatting 
- [x] Clean up `Profile-Info-Form` errors and formatting
- [x] Clean up the `Profile` component to ensure hover feature is working properly
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
