### ISSUE TITLE
Feature 4: User can view their pending matches and accept or decline

### ISSUE THREAD

**Issue by hannahshamb** [hannahnengel/hate-mate#4]
## ⚙️ Feature
User can view their pending matches and accept or decline

## 📐 Functionality
On the home page, the user will have access to their pending matches and choose to accept or decline pending matches based on the information provided. Once a match has been accepted by both users, the match is populated in a list view for the user. If no matches exist for the user, the user is prompted with an option to retake the hate selections quiz. 

## 🖼️ Wireframes
![FEATURE 4-Mobile](https://user-images.githubusercontent.com/90408240/191572176-f6c57692-cb48-4e81-b024-517cf45b7216.png)
![FEATURE 4-Desktop](https://user-images.githubusercontent.com/90408240/191572354-76591e25-c344-4118-8323-95883a2f69a7.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to include a table to save match selections 
- [x] Update `schema.sql` to include a `matches` table that tracks both statuses and match types 

### ☁️ Server

- [x] Update `server/index.js` to pull all user hate selections 
- [x] Update `server/index.js` to pull potential matches from userInfos based on current users friendGender
- [x] Update `server/index.js` to pull potential matches' friendPreferences 
- [x] Update  `server/index.js` to include a get for pulling all selections from `userSelections` by userId
- [x]  Update  `server/index.js` to include a post to push new user match selections to the database 
- [x] Update `server/index.js` to include a post to push new match statuses to the db 
- [x] Update `server/index.js` post request to only post and update match types 
- [x] Update `server/index.js` to include a get user info method to get all the info needed to display on the potential match cards from various tables in the db
- [x] Update `server/index.js` to include a post method to update user and match status
- [x] Refactor code so that the match algorithm to get info of any potential matches runs on only one get request
- [x] Update `server/index.js` a route for getting current user's matches and corresponding info for the Match List page 
- [x] Add a delete and update on "matchSelections" and "matches" for when the user edits their selections when "retaking" the hate quiz or editing a single hate selection
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a `Matches` component
- [x] Update `Matches` component to take the user back to the hate selections quiz when clicking the Retake Quiz button
- [x] Update  `Matches` component to fetch current user's friendPreferences 
- [x]  Update  `Matches` component to fetch all user infos based on friendGender and add to the potentialMatch list based on friendGender and age (calculate age from birthday provided in response)
- [x] Update `Matches` to fetch friendPreferences of all the potential matches from the previously filtered list 
- [x] Update `Matches` to ensure the potential match is within range of the current user's mileRadius preferences and vice versa based on the potential matches' preferences
- [x] Ensure the current user is a fit / match for the potential user based on all of their preferences
- [x] Pull all the potential matches and the current user selections 
- [x] Compare the current user selections and all potential matches selections and save the data in a match selections array
- [x] Compare the current user selections and all potential matches selections to determine what type of match they are (not a match, average match, perfect match etc)
- [x] Push the new matches match types to the db
- [x] Add in styling for the Potential Match Cards 
- [x] Fill in the Potential Match Cards with the info pulled from the db so the user can view information and accept or decline accordingly
- [x] Handle Submits for accept or decline of each potential match by submitting user status to the db and updating matchStatus accordingly
- [x] Update `Matches` component so that the next match after the user accepts or declines the previous is rendered on the page
- [x] Create a `MatchList` page (that will mount the current user's matches in a list format
- [x] Update `Home` component to render the `Matches` component once the user has completed the hate selections quiz
- [x] Update `MatchList` to find and filter the current user's matches by what is still pending 
- [x] Update the `MatchList` page to render all accepted matches

### 🧑‍⚕️ Clean Up

- [x] Add a loading icon to the page until all the fetches have loaded
- [x] Clean up `Home` loading icon functionality
- [x] Clean up `Profile` and other page errors when user is not yet fully registered (redirect to home message to complete their profile)
- [x] Clean up `PhotoModal` component and `server/index.js` so that when user tries to delete a photo that does not exist, there a nice visual error message
- [x] Clean up `Match` component and `server/index.js` so that as few fetches as possible are being called
- [x] Clean up `Home` component to ensure proper page is being displayed on refresh, etc.
- [x] Fix all async issues in the `Matches` component by refactoring using Promise.all 
- [x] Fix errors from no gender response in index.js and Matches component 
- [x] Fix `ArePointsNear` formula to calculate based on angular distance and return the distance in miles 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
