### ISSUE TITLE
Feature 5: User can view all matches’ profiles

### ISSUE THREAD

**Issue by hannahshamb** [hannahnengel/hate-mate#5]
## ⚙️ Feature
User can view all matches’ profiles

## 📐 Functionality
From the matches list, the user can choose to view each of their match's profile by clicking the provided link in each listing. On their match's profile, they will see their information such as name, location, age, gender, contact info and all of their hate selections. The mutual hate selections will appear highlighted in green. 

## 🖼️ Wireframes
![FEATURE 5_Mobile](https://user-images.githubusercontent.com/90408240/179148099-5ec61b49-a847-4165-9014-74ede2567fa7.png)
![FEATURE 5_Desktop](https://user-images.githubusercontent.com/90408240/179148043-fbb70ef5-0425-4044-99bf-be24aa8c2148.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to fetch corresponding user's profile information to populate to the `HateMateProfile` page
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to display the friend's profile that user wishes to see from the matches list 
- [x] Ensure the app.jsx mounts the new component
- [x] Update component to display the fetched data 
- [x] Update the `MatchList` component to redirect to the `HateMateProfile` component with the correct userId

### 🧑‍⚕️ Clean Up
- [x] Clean up `AuthForm` so that error message shows when user uses wrong sign in
- [x] Clean up `ProfileInfoForm` so that loading icon appears while map is locating / updating
- [x] Clean up `ProfileInfoForm` so user can easily edit the entries for city and zip 
- [x] Clean up `HateSelectionInputs` so that loading icons are working properly 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
