### ISSUE TITLE
Feature 6: User can view a map view of all their matches 

### ISSUE THREAD

**Issue by hannahshamb** [hannahnengel/hate-mate#6]
## ⚙️ Feature
User can view a map view of all their matches 

## 📐 Functionality
When the user navigates to the map page, they see a visual representation of where their matches are roughly located, notated by smiley face icons on the map. When the user hovers over the icons, the corresponding match's info will pop up. 

## 🖼️ Wireframes
![FEATURE 6_Mobile](https://user-images.githubusercontent.com/90408240/179148625-4ae313c6-b1f2-4f54-b963-4f8d2fbfca88.png)
![FEATURE 6_Desktop](https://user-images.githubusercontent.com/90408240/179148722-b0000cdf-f938-4c52-8d1b-9262f583d40b.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to include a method for fetching current user's lat lng, all their matches and respective needed info (lat, lng, gender, firstName etc)
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a `MatchMap` component to display the map on and ensure it is being mounted by app.jsx
- [x] Update `Map` component to check for an action prop to determine which type of map to return based on which page it is coming from 
- [x] Update `MatchMap` component and `Map` component to pass props and display markers and info windows for each match on the returned map

### 🧑‍⚕️ Clean Up

- [x] Clean up styling on the `Matches` page
- [x] Clean up errors on `Photo Modal` and `Profile` component when users are editing their profile pictures
- [x] Clean up match list so that the Match type updated as soon as any new changes have been made to current user's profile
- [x] Clean up match list so that it returns in order sorted by match type (perfect first, not a match last)
- [x] Clean up error handling so if an existing user tries to register a new account using the same email, error message is returned
- [x] Clean up view all and see less functionality on `Matches` component
- [x] Clean up error when user selects my profile when they have not yet finished the quiz
- [x] Clean up `HateMateProfile` so the selections are returned in order by category
- [x] Clean up the `Map` formatting for mobile
- [x] Clean up `MatchList` cards for font sizing
- [x] Clean up `ProfileInfoForm` and `index.jsx` errors
- [x] Clean up misc algorithm and styling errors
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
